name: e2e tests
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: library/node:16-alpine

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 6

      - name: Run tests
        run: npm run test-ci
