name: e2e tests
on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: timbru31/node-alpine-git:18
      # https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001

    services:
      redis:
        image: redis:7-bookworm
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: env
        run: env

      - name: Run tests
        run: npm run test-ci
        env:
          REDIS_CONN_STRING: 'redis://redis:6379'

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
